### ISSUE TITLE
Doesn't work pass data from yaml file

### ISSUE THREAD

**Issue by EvgenyLeukhin** [Shyam-Chen/Web-Cheat-Sheet#4]
If you run build script after that open created html file that will be no data from yaml file.

Something like this 
![Снимок экрана 2024-07-30 в 22 42 51](https://github.com/user-attachments/assets/b97b5c02-04a5-42d0-902a-3e787597c0fc)

**Comment by Shyam-Chen** [comment]
After the `build` command, there will be no data (`yaml`), which is correct. The data injection point occurs on the server side. If you do not need to inject data, you can directly write the text within the template.

Here is the HTML template generated after the `build` command from the link below:
https://github.com/Shyam-Chen/Fastify-Starter/blob/main/app/src/templates/hello-world.html

Below is the link to the entry point for data injection:
https://github.com/Shyam-Chen/Fastify-Starter/blob/main/app/src/routes/email/%2Bhandler.ts#L27

In some cases, such as lists, dynamic data injection is sometimes necessary. The YAML here is just for convenient development and preview simulation.

Note: The template syntax used here is `nunjucks`.
